<?php

/* space == separator */

$emoticons=array();

$emoticons[]=':gasleep: ga-sleep.gif';
$emoticons[]=':gababy: ga-baby.gif';
$emoticons[]=':gabotay: ga-bo-tay.gif';
$emoticons[]=':gacamdong: ga-cam-dong.gif';
$emoticons[]=':gachamhoi: ga-cham-hoi.gif';
$emoticons[]=':gachay: ga-chay.gif';
$emoticons[]=':gacry: ga-cry.gif';
$emoticons[]=':gadance: ga-dance.gif';
$emoticons[]=':gadanhrang: ga-danh-rang.gif';
$emoticons[]=':gadie: ga-die.gif';
$emoticons[]=':gadieu: ga-dieu.gif';
$emoticons[]=':gagian: ga-gian.gif';
$emoticons[]=':gahappy: ga-happy.gif';
$emoticons[]=':gakaraoke: ga-karaoke.gif';
$emoticons[]=':gakenhkieu: ga-kenh-kieu.gif';
$emoticons[]=':galeluoi: ga-le-luoi.gif';
$emoticons[]=':gangap: ga-ngap.gif';
$emoticons[]=':gangu: ga-ngu.gif';
$emoticons[]=':gasacmau: ga-sac-mau.gif';
$emoticons[]=':gasangkien: ga-sang-kien.gif';
$emoticons[]=':gasatthu: ga-sat-thu.gif';
$emoticons[]=':gasayxin: ga-say-xin.gif';
$emoticons[]=':gathapnhang: ga-thap-nhang.gif';
$emoticons[]=':gatotinh: ga-to-tinh.gif';

$emoticons[]=':heo: heo.gif';
$emoticons[]=':alien: alien.png';
$emoticons[]=':angry: angry.png';
$emoticons[]=':blink: blink.png';
$emoticons[]=':blush: blush.png';
$emoticons[]=':cheerful: cheerful.png';
$emoticons[]=':cool: cool.png';
$emoticons[]=':cwy: cwy.png';
$emoticons[]=':devil: devil.png';
$emoticons[]=':dizzy: dizzy.png';
$emoticons[]=':ermm: ermm.png';
$emoticons[]=':getlost: getlost.png';
$emoticons[]=':grin: grin.png';
$emoticons[]=':happy: happy.png';
$emoticons[]=':heart: heart.png';
$emoticons[]=':kissing: kissing.png';
$emoticons[]=':laughing: laughing.png';
$emoticons[]=':ninja: ninja.png';
$emoticons[]=':pinch: pinch.png';
$emoticons[]=':pouty: pouty.png';
$emoticons[]=':sad: sad.png';
$emoticons[]=':shocked: shocked.png';
$emoticons[]=':sick: sick.png';
$emoticons[]=':sideways: sideways.png';
$emoticons[]=':silly: silly.png';
$emoticons[]=':sleeping: sleeping.png';
$emoticons[]=':smile: smile.png';
$emoticons[]=':tongue: tongue.png';
$emoticons[]=':unsure: unsure.png';
$emoticons[]=':w00t: w00t.png';
$emoticons[]=':wassat: wassat.png';
$emoticons[]=':whistling: whistling.png';
$emoticons[]=':wink: wink.png';
$emoticons[]=':wub: wub.png';

$aliases=array();
$aliases[]=':) smile.png';
$aliases[]=':( sad.png';
$aliases[]=';-) wink.png';
$aliases[]=':-) smile.png';
$aliases[]=':-( sad.png';
$aliases[]='lol laughing.png';
$aliases[]='rofl laughing.png';


?>